# Generated by Django 5.1.7 on 2025-03-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_alter_contest_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='voted_submissions',
            field=models.ManyToManyField(blank=True, to='contest.submission'),
        ),
    ]
