# Generated by Django 5.1.7 on 2025-04-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_user_voted_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='claimed_reward',
            field=models.BooleanField(default=False),
        ),
    ]
